### PR TITLE
utility classes

### PR DESCRIPTION
**Pull request by smarcu**

### CODE REVIEW

**Comment by smarcu** [comment]
A utility class used to simplify the authorization using persistence for an authorized request token. If no persisted token found it will initiate the authorization, code provided using the console.

Usage with default providers:

 Token accessToken = CubeSensorsUtils.instance().getAccessToken();
 CubeSensorsApiV1 api = new CubeSensorsApiV1(accessToken);
 api.getDevices();

Or assemble a CubeSensorsUtils setting a custom AuthPersistence or AuthProvider:

 CubeSensorsUtils u = new CubeSensorsUtils();
 u.setAuthProvider(... custom auth provider ...)
 u.setAuthPersistence(... custom persistence ...)
 Token accessToken = u.getAccessToken();
 CubeSensorsApiV1 api = new CubeSensorsApiV1(accessToken);
 api.getDevices();

**Comment by 1337joe** [comment]
My initial thought was that this should be part of the app using the library, not the library itself, but I do see the value in providing a sample implementation that's complete enough to get someone started.

A few issues:
- Unless you're directly interacting with the console use a logger instead of printing to System.out to add flexibility and context to debug/error output.  ConsoleAuthProvider is a good use of System.out because it reads in from the console, CubeSensorsUtils should use a logger (and I'd also say always log the exception on line 87 and have the unauthorized message produced by getAccessToken when it actually tries the authorization).
- I probably won't refuse a merge just for this, but my preference is that the javadoc comments should be complete (all public methods and classes have javadoc comments) and meaningful (params, return values have a description, not just their name listed, though if the method is fully described by it's parameters or returns then no method description text is required).  An initial check on this is running "mvn javadoc:javadoc" and seeing what warnings it prints.
- Why not either use a constructor or factory to create custom CubeSensorsUtils?  As it stands now you could create an instance using the default constructor but it will be invalid (will throw NullPointerException) if you try to use it.  There's no valid use for an uninitialized Utils object so why not force it to be initialized on creation?

**Comment by smarcu** [comment]
Thanks for getting back to me.
I understand your initial thought about adding this utils into the library. My drive behind this is that a library should provide a fully functional basic scenario. Without this utils class, I will have to add this code in another library or ... in all my projects dealing with CubeSensors.
1. you are right, I missed the LOGGER you are using in the other classes. Converted the system call to a logger.
2. Agree, added more javadoc.
3. Created the constructor with injected providers. The idea with factory is nice, but it is just too simple scenario to create a new class just for that. Its up to you if you still want it we can create it.

-- also I have a small suggestion, to use the maven snapshot version and the maven release plugin to do the releases, it will help development and will not force you to increase the version for every change.

**Comment by 1337joe** [comment]
1. I'd meant a static factory method in the existing class, just using a constructor is cleaner but you already had the static instance() method.

This project was my first venture into actually publishing into a public maven repo.  I intend to automate the process using the plugin but for a first pass I was doing everything manually so I'd know what the plugin is doing under the covers.

Your last pull request resulted in an immediate version bump and release because I'd already been meaning to push a release ever since the noise units change and the pull request reminded me to get to it.  I'll use snapshot when I've got the plugin set up, which will probably be after I've set it up at work since I'm in the middle of redoing our build there to use maven.

**Pull request merged**
